version: '3'
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  postgres_db_test:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  mongo_db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    # environment:
    #   POSTGRES_PASSWORD: mysecretpassword
  mysql_db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
